create database ptest ; 
use ptest ; 
drop table buyer;
create table buyer ( name text not null, familyname text not null, username text not null, password text not null, primary key (username(20))) ; 
insert into buyer values ( 'Thomas', 'Poulain', 'thomaspln', 'password') ; 
insert into buyer values ( 'Capucine', 'Plantecoste', 'capuplt', 'thisismypassword'); 
insert into buyer values ( 'Emmanuel', 'Macron', 'manu', 'president') ; 
insert into buyer values ( 'Franck', 'Poulain', 'franckpln', 'microsoft123') ; 
insert into buyer values ( 'Laurence', 'Godnair', 'laurencegdr', 'melann!') ; 
insert into buyer values ( 'Killian', 'Poulain', 'killianpln', '123456') ; 
select * from buyer ;

drop table employee;
create table employee (name text not null, familyname text not null, username text not null, password text not null, primary key (username(20))) ; 
insert into employee values ( 'Pauline', 'Durand', 'paulinedrd', '12345') ; 
insert into employee values ( 'Cathleen', 'West', 'cathwest', 'heyhey'); 
insert into employee values ( 'John', 'Dalton', 'joedltn', 'ineedapassword') ; 
insert into employee values ( 'Marie', 'Lebourg', 'marielbg', 'secret') ; 
insert into employee values ( 'Therese', 'Marcoux', 'thmarcoux', 'changeme') ; 
insert into employee values ( 'Joe', 'Biden', 'joebdn', 'usapresident') ; 
select * from employee ;

drop table apartment;
create table apartment (id int not null, price double not null, location text not null, numberrooms int not null, numberbedrooms int not null, timevisited int not null, numberfloors int not null, surface double not null, elevator bool not null, floornumber int not null, parking bool not null, primary key (id)) ; 
insert into apartment values (100, 245000, 'Paris 15', 3, 2, 3, 1, 50, false, 3, false) ; 
insert into apartment values (101, 1000000, 'Paris 1', 5, 3, 10, 1, 75, false, 2, false); 
insert into apartment values (102, 1300000, 'Paris 2', 6, 3, 32, 2, 95, true, 3, true) ; 
insert into apartment values (103, 250000, 'Paris 6', 3, 2, 7, 1, 35, false, 1, false) ; 
insert into apartment values (104, 6000000, 'Paris 3', 6, 4, 5, 2, 120, true, 5, true) ; 
insert into apartment values (105, 900000, 'Paris 4', 4, 2, 17, 1, 102, true, 4, false) ; 
select * from apartment ;

drop table house;
create table house (id int not null, price double not null, location text not null, numberrooms int not null, numberbedrooms int not null, timevisited int not null, numberfloors int not null, surface double not null, gardensurface double not null, swimmingpool bool, primary key (id));
insert into house values (01, 170000, 'Paris 12', 4, 2, 3 , 2 , 120, 40, false);
insert into house values( 02, 1000000, 'Baden', 8, 5, 10, 3, 1000, 200, false);
insert into house values (03, 1300000, 'Nice', 6, 3, 5, 3, 1200, 500, true);
insert into house values (04, 230000, 'Trouville', 5, 3, 7, 5, 40, 5, false);
insert into house values (05, 6000000, 'Saint-Tropez', 6, 4, 35, 2, 500, 200, true);
insert into house values (06, 900000, 'Le Pecq', 6, 3, 17, 3, 1000, 700, false);

drop table seller;
create table seller ( name text, familyname text, username text, password text, primary key (username(20))) ; 
insert into seller values ( 'Apolline', 'Cherrey', 'apocherrey', 'lili123') ; 
insert into seller values ( 'Lilian', 'Biscarrat', 'lilibisc', 'thais'); 
insert into seller values ( 'Henri', 'Petrelli', 'henriptl', 'corsica') ; 
insert into seller values ( 'Thierry', 'Cancelier', 'thierryplt', 'trouville') ; 
insert into seller values ( 'Delphine', 'Fontaine', 'delphineplt', 'jetmonchat') ; 
insert into seller values ( 'Cassandre', 'Ferrand', 'cassandreplt', '123456') ; 
select * from seller ;