//seller first is the first jframe that appears after a seller connected 
package View;

import Model.Visit;
import Model.Seller;
import Model.Property;
import Model.Offer;
import Model.Employee;
import Model.Buyer;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import projectjava.First;

/**
 *
 * @author CAP
 */
public class SellerFirst extends javax.swing.JFrame {

    /**
     * Creates new form SellerFirst
     */
    public SellerFirst(Seller a, ArrayList<Buyer> b, ArrayList<Seller> s, ArrayList<Employee> e, ArrayList<Property> prop, ArrayList<Visit> vis, ArrayList<Offer> off) {
        //constructor of the class
        buyers = b;
        //Array List of all the buyers of the application
        sellers = s;
        //Array List of all the sellers of the application
        emp = e;
        //Array List of all the employees of the application
        pr = prop;
        //Array List of all the properties of the application
        v = vis;
        //Array List of all the viewings of the application
        o = off;
        //Array List of all the offers of the application
        newseller = a;
        //current connected seller 
        initComponents();
        //automatically generated constructor
        this.nom();
        //function that enables to show the name of the seller when he connects 

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectjava/logo 2 projet info.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(312, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(198, 198, 198)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel2.add(jPanel4);
        jPanel4.setBounds(0, 0, 740, 830);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButton5.setText("Log Out");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(1360, 100, 100, 23);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButton1.setText("See my offers");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(1030, 420, 340, 40);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButton2.setText("Delete a viewing of one of my properties");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(1030, 580, 340, 40);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButton3.setText("Introduce new property");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(1030, 340, 340, 40);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButton4.setText("See my current properties");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(1030, 260, 340, 40);

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButton6.setText("Add a viewing to one of my properties");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(1030, 500, 340, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1575, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // log out button
        this.toBack();
        //when we click on the button
        setVisible(false);
        //this page disappears 
        new First(buyers, sellers, emp, pr, v, o).toFront();
        //we go back on the first page 
        new First(buyers, sellers, emp, pr, v, o).setState(java.awt.Frame.NORMAL);
        new First(buyers, sellers, emp, pr, v, o).setVisible(true);
        //we set the first page to visible 
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //introduce a new property button
        this.setVisible(false);
        //this frame disappeears 
        new SellerNewProperty(newseller, buyers, sellers, emp, pr, v, o).setVisible(true);
        //we open the next new frame 
        new SellerNewProperty(newseller, buyers, sellers, emp, pr, v, o).toFront();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // delete a viewing of one of the seller property button
        ArrayList<Property> propviewing = new ArrayList<>();
        //the create an array list of properties called prop viewings that will contain all the properties of the sellers that have at least one viewing 
        myviewings.clear();
        //we clear the array list that contained all the viewings of the seller 
        this.setmyviewings();
        //we set the viewings of the seller and we add the sellers viewings in my viewings 
        for (int i = 0; i < myviewings.size(); ++i) {
            //we go through the viewings of the seller 
            for (int j = 0; j < myprop.size(); ++j) {
                // we go through the properties of the connected seller 
                if ((myviewings.get(i).getidprop() == myprop.get(j).getid()) && (!propviewing.contains(myprop.get(j)))) {
                    //if the id of the property of one of the viewings is the same as the id of the considered property and if the property is not already contained in the list
                    propviewing.add(myprop.get(j));
                    //we add this property to the array list of property called propviewing 
                }
            }
        }
        if (propviewing.isEmpty()) {
            //if there is no property that has at least one viewing 
            JOptionPane.showMessageDialog(null, "No visit found for any of your properties");
            //we say so
        } else {
            //otherwise
            this.setVisible(false);
            //we open a new frame so we have to close this one
            SellerDeleteViewing a = new SellerDeleteViewing(newseller, buyers, sellers, emp, pr, v, o, myviewings, propviewing);
            //we open the next frame
            a.setVisible(true);
            //we set the next frame visible
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //See my offers button
        myoffers.clear();
        //first, we clean the array list of the offers of the connected seller
        this.setmyoffers();
        //we set the offers of the seller and we add the sellers offers in my offers 
        if (myoffers.isEmpty()) {
            //if the seller has no offer 
            JOptionPane.showMessageDialog(null, "No offers made for one of your properties or you don't have any property"); //message shown to say so
            //message to say so
        } else {
            //otherwise
            this.setVisible(false);
            //we open a new frame so we have to close this one 
            SellerOffer a = new SellerOffer(newseller, buyers, sellers, emp, pr, v, o, myoffers);
            //we open the next frame
            a.setVisible(true);
            //we set the next frame visible
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // See my current properties button
        myprop.clear();
        //first, we clear the array list of the properties of the connected seller
        this.setmyprop();
        //we set the properties of the seller and we add the sellers properties in my prop

        if (myprop.isEmpty()) {
            //if the seller has no properties 
            JOptionPane.showMessageDialog(null, "You have no properties for sale"); //message shown to say so
            //message to say so
        } else {
            //otherwise
            this.setVisible(false);
            //we open a new frame so we have to close this one 
            SellerProperty a = new SellerProperty(newseller, buyers, sellers, emp, pr, v, o, myprop);
            //we open the next frame
            a.setVisible(true);
            //we set the next frame visible
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //add a viewing to one of my property button
        myprop.clear();
        //first, we clear the array list of the properties of the connected seller
        this.setmyprop();
        //we set the properties of the seller and we add the sellers properties in my prop
        if (myprop.isEmpty()) {
        //if the seller has no properties 
            JOptionPane.showMessageDialog(null, "You have no properties for sale so you cannot add no viewings"); //message shown to say so
            //message to say so 
        } else {
            //otherwise
            this.setVisible(false);
            //we open a new frame so we have to close this one 
            SellerAddViewing a = new SellerAddViewing(newseller, buyers, sellers, emp, pr, v, o, myprop);
            //we open the next frame
            a.setVisible(true);
            //we set the next frame visible
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    public void nom() {
        //function that is used to display the name of the seller when he first connects 
        jLabel1.setText("We are very pleased to see you again " + newseller.getname() + "!");
        // we fill the field with the name of the seller 
    }

    public void setmyprop() {
        //function that adds the seller properties in the arraylist myprop
        for (int i = 0; i < pr.size(); ++i) {
            //we go through the all the properties of the application            
            if (pr.get(i).getidseller() == newseller.getid() && !myprop.contains(pr.get(i))) {
                //As we call the setmyprop method in several places, we have to make sure that we don't have twice the same property so we use the contains method
                myprop.add(pr.get(i));
                //we add the property in the personal properties list of the connected seller 
            }
        }
    }

    public void setmyoffers() {
        //function that adds the seller offers in the arraylist myoffers
        myprop.clear();
        //we clear the personal properties of the seller  
        this.setmyprop();
        //we set the properties of the seller and we add the sellers properties in my prop
        
        for (int i = 0; i < o.size(); ++i) {
            //we go through the offers of the application 
            for (int j = 0; j < myprop.size(); ++j) {
                //we go through the personal properties of the connected seller 
                if (o.get(i).getidprop() == myprop.get(j).getid() && (o.get(i).getdeclined() == false) && (myprop.get(j).getsold() == false)) {
                    //if the id of the property of the offer is the same as the id of the considered property and the property of the offer has not been declined and is not sold 
                    myoffers.add(o.get(i));
                    //we add the offer in the personal offers list of the connected seller 
                }
            }
        }
    }

    public void setmyviewings() {
        //function that adds the seller viewings in the arraylist myviewings
        myprop.clear();
        //we clear the personal properties of the seller
        this.setmyprop();
        //we set the properties of the seller and we add the sellers properties in my prop
        for (int i = 0; i < v.size(); ++i) {
            //we go through the viewings of the application 
            for (int j = 0; j < myprop.size(); ++j) {
                //we go through the personal properties of the connected seller 
                if (v.get(i).getidprop() == myprop.get(j).getid()) {
                    // if the id of the property of the viewing is the same as the id of the considered property 
                    myviewings.add(v.get(i));
                    //we add the viewing in the personal viewings list of the connected seller 
                }
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellerFirst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellerFirst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellerFirst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellerFirst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new SellerFirst(newseller, buyers, sellers, emp, pr, v, o).setVisible(true);

            }
        });
    }

    private static ArrayList<Buyer> buyers = new ArrayList<>();
    //array list of all the application buyers 
    private static ArrayList<Seller> sellers = new ArrayList<>();
    //array list of all the application sellers 
    private static ArrayList<Employee> emp = new ArrayList<>();
    //array list of all the application employees 
    private static ArrayList<Property> pr = new ArrayList<>();
    //array list of all the application properties
    private static ArrayList<Visit> v = new ArrayList<>();
    //array list of all the application viewings
    private static ArrayList<Offer> o = new ArrayList<>();
    //array list of all the application offers

    private static ArrayList<Property> myprop = new ArrayList<>();
    //array list of all the personal seller properties
    private static ArrayList<Offer> myoffers = new ArrayList<>();
    //array list of all the personal seller offers
    private static ArrayList<Visit> myviewings = new ArrayList<>();
    //array list of all the personal seller viewings

    private static Seller newseller;
    //current connected seller 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
